package io.casehub.qhorus.api.compliance.report;

public enum ReportType {
    ATTRIBUTION, OBLIGATION, TRUST_HISTORY, VIOLATION, PROVENANCE,
    JUDGMENT_ATTRIBUTION, JUDGMENT_FULFILLMENT, PROPERTY_VERIFICATION
}
