package io.casehub.qhorus.compliance.model;

public enum ReportType {
    ATTRIBUTION, OBLIGATION, TRUST_HISTORY, VIOLATION, PROVENANCE,
    JUDGMENT_ATTRIBUTION, JUDGMENT_FULFILLMENT, PROPERTY_VERIFICATION
}
