CREATE TABLE channel_membership (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id UUID NOT NULL,
    member_id VARCHAR(255) NOT NULL,
    member_role VARCHAR(50) NOT NULL,
    tenancy_id VARCHAR(255) NOT NULL DEFAULT '278776f9-e1b0-46fb-9032-8bddebdcf9ce',
    joined_at TIMESTAMP NOT NULL,
    last_read_message_id BIGINT,
    CONSTRAINT uq_membership_channel_member UNIQUE (channel_id, member_id),
    CONSTRAINT fk_membership_channel FOREIGN KEY (channel_id) REFERENCES channel(id) ON DELETE CASCADE
);
CREATE INDEX idx_membership_member_id ON channel_membership(member_id);
